In [9]:
import cv2
import os

# 指定图像文件路径
image_dir = '.'
image_files = ['DSC6984.JPG', 'DSC6984.JPG', 'DSC6984.JPG']
img=cv2.imread(image_files[0])
print('image_files:', img)

image_files: [[[146 150 151]
  [143 148 147]
  [146 151 150]
  ...
  [220 218 217]
  [220 218 217]
  [218 218 218]]

 [[145 149 150]
  [147 152 151]
  [146 150 151]
  ...
  [220 218 217]
  [220 218 217]
  [218 218 218]]

 [[146 151 150]
  [145 150 149]
  [147 149 150]
  ...
  [218 219 217]
  [220 218 217]
  [220 218 217]]

 ...

 [[205 203 202]
  [204 203 199]
  [205 204 200]
  ...
  [200 200 200]
  [201 201 201]
  [201 201 201]]

 [[204 202 201]
  [205 204 200]
  [205 204 200]
  ...
  [200 200 200]
  [200 200 200]
  [201 201 201]]

 [[206 202 201]
  [204 203 199]
  [206 202 201]
  ...
  [199 199 199]
  [201 201 201]
  [201 201 201]]]


In [19]:
import cv2
import numpy as np

# 读取图片
img1 = cv2.imread('DSC6984.jpg')
img2 = cv2.imread('DSC6986.jpg')
img3 = cv2.imread('DSC6987.jpg')

# 获取图片尺寸
height, width, layers = img1.shape

# 定义视频的编码器及相关参数
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
video = cv2.VideoWriter('output_video.mp4', fourcc, 5, (width, height))

# 将图片重复5次，每张图片显示1秒（3帧）
images = [img1, img2, img3]
for _ in range(10):  # 循环5次
    for img in images:
        for _ in range(1):  # 每张图片显示1秒（10帧）
            video.write(img)

# 释放视频对象
video.release()

print("视频已生成并保存为output_video.mp4")

视频已生成并保存为output_video.mp4


In [ ]:
import cv2
import os
from PIL import Image

# 指定图像文件路径
image_dir = '.'  # 你的图像目录
image_files = ['a.jpg', 'b.jpg', 'c.jpg']  # 你的图像文件名

# 获取第一张图像的大小,用于设置视频大小
image_path = os.path.join(image_dir, image_files[0])
image = Image.open(image_path)
width, height = image.size

# 设置视频编码器和FPS
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
fps = 1  # 每张图像显示1秒
frame_count = 5 * len(image_files)  # 总帧数

# 创建视频写入对象
out = cv2.VideoWriter('output.mp4', fourcc, fps, (width, height))

# 循环读取图像并写入视频
for _ in range(5):  # 循环5次
    for image_file in image_files:
        image_path = os.path.join(image_dir, image_file)
        image = cv2.imread(image_path)
        out.write(image)

out.release()
cv2.destroyAllWindows()

In [4]:
import cv2
import numpy as np
import os

# 读取图片文件夹中的所有图片
folder_path = 'mmgfig'
images = []

# 遍历文件夹中的所有文件，并将图片文件添加到列表中
for filename in sorted(os.listdir(folder_path)):
    if filename.endswith('.JPG') or filename.endswith('.png'):  # 添加其他图片格式如有需要
        img = cv2.imread(os.path.join(folder_path, filename))
        if img is not None:
            images.append(img)

# 检查是否有读取到图片
if not images:
    raise Exception("没有找到任何图片文件，请检查文件夹路径和文件格式")

# 获取图片尺寸
height, width, layers = images[0].shape

# 定义视频的编码器及相关参数
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
video = cv2.VideoWriter('output_video-1.mp4', fourcc, 15, (width, height))

# 将图片写入视频，每张图片作为一帧
for img in images:
    video.write(img)

# 释放视频对象
video.release()

print("视频已生成并保存为output_video.mp4")


视频已生成并保存为output_video.mp4
