In [1]:
import pandas as pd
import torch
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from torch.utils.data import TensorDataset, DataLoader
import os
import cv2 as cv
from torch.utils.data import Dataset
from torchvision import transforms
import torch.nn.functional as F
from PIL import Image
import torch.nn as nn
from torch.optim import Adam
import matplotlib.pyplot as plt
import numpy as np
from torch.autograd import Variable

# Define the data and label

In [2]:
def getlabel(dir):
    labels=[]
    for name in os.listdir(dir):
        if os.path.splitext(name)[1] == '.png':
            fname=os.path.splitext(name)[0]
            labels.append(fname)
    labels = list(map(int, labels))
    labels = torch.tensor(labels)
    # Normalize labels
    #min = torch.min(labels)
    #max = torch.max(labels)
    #labels = (labels - min) / (max - min)
    labels = labels.type(torch.FloatTensor)
    return labels

def generate_dataset(dir):
    """
    set_label should be 'torch.tensor([1])' if two-catogory and positive sample
    """
    train_data = []
    for file_name in os.listdir(dir):
        img_dir = os.path.join(dir, file_name)
        img = cv.imread(img_dir)
        img = cv.resize(img, (769, 432))   # /5 resize img
        #img_gray = cv.cvtColor(img,cv.COLOR_RGB2GRAY)
        pimg = Image.fromarray(img)
        train_data.append(pimg)
    return train_data

In [3]:
traindir= './train/'
validdir = './test/'
train_data0 = generate_dataset(traindir)
train_label0=getlabel(traindir)
valid_data0 = generate_dataset(validdir)
valid_label0 = getlabel(validdir)


In [4]:
train_label0

tensor([  0.,   1.,  10., 100., 101., 102., 103., 104., 105., 106., 107., 108.,
        109.,  11., 110., 111., 112., 113., 114., 115., 116., 117., 118., 119.,
         12., 120., 122., 123., 124., 125., 126., 129.,  13., 130., 132., 133.,
        134., 135., 136., 137., 138., 139.,  14., 140., 141., 142., 143., 144.,
        145., 146., 147., 148., 149.,  15., 150., 151., 152., 153., 154., 155.,
        156., 157., 159.,  16., 160., 162., 163., 164., 165., 166., 167., 168.,
        169.,  17., 170., 171., 172., 173., 174., 175., 176., 177., 178., 179.,
         18., 180., 182., 183., 184., 185., 186., 189.,  19., 190., 191., 192.,
        193., 194., 195., 196., 197., 198., 199.,   2.,  20., 200., 201., 203.,
        204., 205.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,   3.,
         30.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,   4.,  43.,  44.,
         45.,  46.,  47.,  48.,  49.,   5.,  50.,  51.,  52.,  53.,  54.,  55.,
         56.,  57.,  58.,   6.,  60.,  6

# 重写dataset类

In [5]:
class MyDataset(Dataset):
    def __init__(self, data, labels, transform=None, target_transform=None):
        self.transform = transform
        self.target_transform = target_transform
        imgs = []
        for i in range(len(labels)):
            # print(type(data[i]))    # <class 'PIL.Image.Image'>
            im_tensor = transform(data[i])#.to(torch.device("cpu"))
            imgs.append((im_tensor, labels[i]))
        self.imgs = imgs                         # DataLoader通过getitem读取图片数据
    def __getitem__(self, index):
        fn, label = self.imgs[index]
        return fn, label
    def __len__(self):
        return len(self.imgs)
    

# 用MyDataset构建数据集

In [6]:
normMean = [0.5, 0.5, 0.5]
normStd = [0.5, 0.5, 0.5]
transform = transforms.Compose(
    [transforms.Grayscale(num_output_channels=1), #彩色图像转灰度图像num_output_channels默认1
    transforms.ToTensor(),  # range [0, 255] -> [0.0,1.0]   
    #transforms.Normalize(normMean, normStd)
    ])

# 也可以再定义train_transform加入一些数据增强 
train_data = MyDataset(train_data0, train_label0, transform=transform)
valid_data = MyDataset(valid_data0, valid_label0, transform=transform)
train_loader = DataLoader(dataset=train_data, batch_size=1, shuffle=True)
valid_loader = DataLoader(dataset=valid_data, batch_size=1, shuffle=True)
dataiter=iter(train_loader)
images, labels = dataiter.next()
print(images.shape)
print(labels.shape)

torch.Size([1, 1, 432, 769])
torch.Size([1])


In [7]:
len(train_label0)

187

# 定义网络

In [8]:
class Net(torch.nn.Module):
    # Net类的初始化函数
    def __init__(self, n_feature, n_hidden, n_output):
        # 继承父类的初始化函数
        super(Net, self).__init__()
        # 网络的隐藏层创建，名称可以随便起
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=3, kernel_size=3, stride=1, padding=1)
        self.bn1 = nn.BatchNorm2d(3)
        self.conv2 = nn.Conv2d(in_channels=3, out_channels=6, kernel_size=3, stride=1, padding=1)
        self.bn2 = nn.BatchNorm2d(6)
        self.pool = nn.MaxPool2d(2,2)
        self.fc1 = nn.Linear(6*108*192, n_feature)
        self.hidden_layer = torch.nn.Linear(n_feature, n_hidden)
        # 输出层(预测层)创建，接收来自隐含层的数据
        self.predict_layer = torch.nn.Linear(n_hidden, n_output)

    # 网络的前向传播函数，构造计算图
    def forward(self, x):
        x = self.pool(F.relu(self.bn1(self.conv1(x))))      #432-3+1=430,430/2=215;769-3+1=767,767/2=384
        x = F.relu(self.bn2(self.conv2(x)))                #215-3+1=213,213/2=108;384-3+1=382,382/2=192
        x = self.pool(x)   
        x = x.view(-1, 6*108*192)
        x = F.relu(self.fc1(x))
        # 用relu函数处理隐含层输出的结果并传给输出层
        hidden_result = self.hidden_layer(x)
        relu_result = F.relu(hidden_result)
        predict_result = self.predict_layer(relu_result)
        return predict_result

In [9]:
def testAccuracy():
    
    net.eval()
    accuracy = 0.0
    total = 0.0
    #device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    device = torch.device("cpu")

    with torch.no_grad():
        for data in valid_loader:
            images, labels = data
            images, labels = images.to(device), labels.to(device)
            # run the model on the test set to predict labels
            outputs = net(images)
            # the label with the highest energy will be our prediction
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            accuracy += (predicted == labels).sum().item()
    
    # compute the accuracy over all test images
    accuracy = (100 * accuracy / total)
    return(accuracy)

def train(num_epochs):
    
    best_accuracy = 0.0

    # Define your execution device
    #device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    device = torch.device("cpu")

    # Convert model parameters and buffers to CPU or Cuda
    net.to(device)
    for epoch in range(num_epochs):  # loop over the dataset multiple times
        running_loss = 0.0
        running_acc = 0.0

        for i, (images, labels) in enumerate(train_loader, 0):
            #images, labels = dataiter.next()
            # 输入数据进行预测
            # get the inputs
            images = Variable(images.to(device))
            labels = Variable(labels.to(device))
            prediction = net(images)
            print(prediction,labels)
            # 计算预测值与真值误差，注意参数顺序问题
            # 第一个参数为预测值，第二个为真值
            loss = loss_func(prediction, labels)

            # 开始优化步骤
            # 每次开始优化前将梯度置为0
            optimizer.zero_grad()
            # 误差反向传播
            loss.backward()
            # 按照最小loss优化参数
            optimizer.step()
            print('epoch:',i,'loss:',loss.item())
            if i % 1000 == 999:    
                # print every 1000 (twice per epoch) 
                print('[%d, %5d] loss: %.3f' %
                      (epoch + 1, i + 1, running_loss / 1000))
                # zero the loss
                running_loss = 0.0
        # 计算准确率
        # Compute and print the average accuracy fo this epoch when tested over all 10000 test images
        accuracy = testAccuracy()
        print('For epoch', epoch+1,'the test accuracy over the whole test set is %d %%' % (accuracy))


    print('Finished Training')
        #可视化训练结果
        # if i % 2 == 0:
        #     # 清空上一次显示结果
        #     plt.cla()
        #     # 无误差真值曲线
        #     plt.plot(images.numpy(), labels.numpy(), c='blue', lw='3')
        #     # 有误差散点
        #     plt.scatter(images.numpy(), labels.numpy(), c='orange')
        #     # 实时预测的曲线
        #     plt.plot(images.numpy(), prediction.data.numpy(), c='red', lw='2')
        #     plt.text(-0.5, -65, 'Time=%d Loss=%.4f' % (i, loss.data.numpy()), fontdict={'size': 15, 'color': 'red'})
        #     plt.pause(0.1)

In [10]:
Vdataiter=iter(valid_loader)
vimg, vlabels = Vdataiter.next()
print(vimg.shape)
print(vlabels.shape)
print(vlabels)

torch.Size([1, 1, 432, 769])
torch.Size([1])
tensor([72.])


## 预测结果

In [11]:
def predict(model, device):
    Vdataiter=iter(valid_loader)
    vimg, vlabels = Vdataiter.next()
    model.to(device)
    with torch.no_grad():
        vimg=vimg.to(device)
        out = model(vimg)
        #_, pre = torch.max(out.data, 1)
        return vimg,out, vlabels

# 定义模型

In [12]:
# 训练次数
TRAIN_TIMES = len(train_loader)-1
# 输入输出的数据维度，这里都是1维
INPUT_FEATURE_DIM = 1000
OUTPUT_FEATURE_DIM = 1
# 隐含层中神经元的个数
NEURON_NUM = 200
# 学习率，越大学的越快，但也容易造成不稳定，准确率上下波动的情况
LEARNING_RATE = 0.1
# unsqueeze函数可以将一维数据变成二维数据，在torch中只能处理二维数据
#x_data = torch.unsqueeze(torch.linspace(-4, 4, 80), dim=1)
# randn函数用于生成服从正态分布的随机数
#y_data = x_data.pow(3) + 3 * torch.randn(x_data.size())
#y_data_real = x_data.pow(3)

# 定义模型
net = Net(n_feature=INPUT_FEATURE_DIM, n_hidden=NEURON_NUM, n_output=OUTPUT_FEATURE_DIM)
print(net)
# 训练网络
# 这里也可以使用其它的优化方法
optimizer = torch.optim.Adam(net.parameters(), lr=LEARNING_RATE)
# 定义一个误差计算方法
loss_func = torch.nn.MSELoss() # 定义交叉熵损失函数 交叉熵损失函数是用来衡量两个概率分布之间的距离的#nn.MSELoss()
# Define the loss function with Classification Cross-Entropy loss and an optimizer with Adam optimizer

Net(
  (conv1): Conv2d(1, 3, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (bn1): BatchNorm2d(3, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv2): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (bn2): BatchNorm2d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=124416, out_features=1000, bias=True)
  (hidden_layer): Linear(in_features=1000, out_features=200, bias=True)
  (predict_layer): Linear(in_features=200, out_features=1, bias=True)
)


# 主函数

In [13]:
# Vdataiter=iter(valid_loader)
# vimg, vlabels = Vdataiter.next()
# print(vimg.shape)
# print(vlabels.shape)
# print(vlabels)
if __name__ == "__main__":

    torch.cuda.empty_cache()
    
    #device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    device = torch.device("cpu")
    # Let's build our model
    train(5)
    print('Finished Training')

    # Test which classes performed well
    testAccuracy()
    
    # Let's load the model we just created and test the accuracy per label
    # model = net()
    # path = "myFirstModel.pth"
    # model.load_state_dict(torch.load(path))

    print(predict(net, device))


tensor([[0.0053]], grad_fn=<AddmmBackward0>) tensor([140.])


c:\Users\brcy\anaconda3\envs\pytorch-cy1\lib\site-packages\torch\nn\modules\loss.py:530: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


epoch: 0 loss: 19598.525390625
tensor([[735849.8750]], grad_fn=<AddmmBackward0>) tensor([43.])
epoch: 1 loss: 541411770368.0
tensor([[-35180.9805]], grad_fn=<AddmmBackward0>) tensor([169.])
epoch: 2 loss: 1249621120.0
tensor([[159564.5000]], grad_fn=<AddmmBackward0>) tensor([175.])
epoch: 3 loss: 25405011968.0
tensor([[-4647.2036]], grad_fn=<AddmmBackward0>) tensor([185.])
epoch: 4 loss: 23350192.0
tensor([[-628.1287]], grad_fn=<AddmmBackward0>) tensor([33.])
epoch: 5 loss: 437091.1875
tensor([[7590.9937]], grad_fn=<AddmmBackward0>) tensor([54.])
epoch: 6 loss: 56806272.0
tensor([[-2259.6536]], grad_fn=<AddmmBackward0>) tensor([48.])
epoch: 7 loss: 5325265.0
tensor([[-375.0234]], grad_fn=<AddmmBackward0>) tensor([65.])
epoch: 8 loss: 193620.578125
tensor([[1202.5931]], grad_fn=<AddmmBackward0>) tensor([45.])
epoch: 9 loss: 1340021.875
tensor([[-95.9383]], grad_fn=<AddmmBackward0>) tensor([198.])
epoch: 10 loss: 86399.71875
tensor([[722.3667]], grad_fn=<AddmmBackward0>) tensor([16.])
ep